appVersion: v1
kind: configmap
metadata:
  name: app-config
  namespace: default
data:
 APP_ENV: "production"
 lOG_LEVEL: "info"
---
appVersion: v1
kind: secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "mysecretpassword"  
