apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
 APP_ENV: "production"
 lOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "mysecretpassword"  
