pipeline {

    agent any

    environment {
        IMAGE_NAME      = "deekshithc1/simplenodeapp"
        DEPLOYMENT_NAME = "node-app"
        NAMESPACE       = "node-app"
    }

    stages {

        stage("Checkout Code") {
            steps {
                checkout scm
            }
        }


        stage("Secret Detection") {
            steps {
                sh '''
                    gitleaks detect \
                    --source . \
                    --no-git \
                    --verbose \
                    --exit-code 1 \
                    --no-banner
                '''
            }
        }


        stage("SonarQube Analysis") {
            steps {

                dir("Assignment/Assignment6") {

                    script {

                        def scannerHome = tool "SonarScanner"

                        withSonarQubeEnv("SonarQube") {

                            sh """
                                ${scannerHome}/bin/sonar-scanner
                            """
                        }
                    }
                }
            }
        }


        stage("SonarQube Quality Gate") {
            steps {

                timeout(
                    time: 5,
                    unit: 'MINUTES'
                ) {

                    waitForQualityGate abortPipeline: true
                }
            }
        }


        stage("Build Docker Image") {
            steps {

                sh """
                    docker build \
                    -t ${IMAGE_NAME}:${BUILD_NUMBER} \
                    -f Assignment/Assignment6/app/Dockerfile \
                    Assignment/Assignment6/app
                """
            }
        }


        stage("Trivy Image Scan") {
            steps {

                sh """
                    trivy image \
                    --severity HIGH,CRITICAL \
                    --exit-code 1 \
                    ${IMAGE_NAME}:${BUILD_NUMBER}
                """
            }
        }


        stage("DockerHub Login") {

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS'
                    )
                ]) {

                    sh '''
                        echo $PASS | docker login \
                        -u $USER \
                        --password-stdin
                    '''
                }
            }
        }


        stage("Push Docker Image") {

            steps {

                sh """

                    docker tag \
                    ${IMAGE_NAME}:${BUILD_NUMBER} \
                    ${IMAGE_NAME}:latest


                    docker push \
                    ${IMAGE_NAME}:${BUILD_NUMBER}


                    docker push \
                    ${IMAGE_NAME}:latest

                """
            }
        }


       


        stage("Deploy to Kubernetes") {

            steps {

                withKubeConfig(
                    credentialsId: 'my-kubeconfig'
                ) {

                    sh """

                        kubectl apply \
                        -f Assignment/Assignment6/K8s/namespace.yaml


                        kubectl apply \
                        -f Assignment/Assignment6/K8s/development.yaml


                        kubectl apply \
                        -f Assignment/Assignment6/K8s/service.yaml


                        kubectl set image \
                        deployment/${DEPLOYMENT_NAME} \
                        node-app=${IMAGE_NAME}:${BUILD_NUMBER} \
                        -n ${NAMESPACE}


                        kubectl rollout status \
                        deployment/${DEPLOYMENT_NAME} \
                        -n ${NAMESPACE} \
                        --timeout=120s


                        kubectl get pods \
                        -n ${NAMESPACE}


                        echo "Deployment completed successfully"

                    """
                }
            }
        }

    }


    post {

        always {

            echo "======== Pipeline Finished ========"

        }


        success {

            echo "======== Pipeline executed successfully ========"

        }


        failure {

            echo "======== Pipeline execution failed ========"

        }

    }

}