pipeline{
    agent any

    environment{
        AWS_ACCOUNT_ID = '127916168511'
        AWS_REGION = 'ap-south-2'
        ECR_REPOSITORY = 'node-demo-app'
        IMAGE_TAG = 'v1'
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}"
    }
    stages{
        stage("Checkout Code"){
            steps{
                echo "checkout scm"
            }
        }
        stage('Verify tools') {
            steps {
                sh '''
                aws --version
                docker --version
                git --version
                '''
            }
        }
        stage('Login to AWS ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }
        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${ECR_REPOSITORY}:${IMAGE_TAG} /Practice/Docker/Node/Dockerfile
                '''
            }
        }
        // stage('Tag Docker Image') {
        //     steps {
        //         sh '''
        //         docker tag ${ECR_REPOSITORY}:${IMAGE_TAG} ${ECR_REGISTRY}
        //         '''
        //     } 
        // }
        // stage('Push Docker Image to ECR') {
        //     steps {
        //         sh '''
        //         docker push ${ECR_REGISTRY}
        //         '''
        //     }
        // }
    }
    post{
        success {
           echo "Docker image pushed successfully to AWS ECR: ${IMAGE_URI}"
       }

       failure {
           echo "Pipeline failed. Check Jenkins console logs."
       }
    }
}