pipeline {

    agent any

    environment {
        IMAGE_NAME = "deekshithc1/simplenodeapp"
        DEPLOYMENT_NAME = "node-app"
        NAMESPACE = "node-app"
    }

    stages {

        stage("Checkout Code") {
            steps {
                checkout scm
            }
        }


        stage("SonarQube Analysis") {
            steps {

                dir('Assignment/Assignment5') {

                    script {

                        def scannerHome = tool 'SonarScanner'

                        withSonarQubeEnv('SonarQube') {

                            sh """
                                ${scannerHome}/bin/sonar-scanner
                            """

                        }

                    }

                }

            }
        }


        stage("Build Docker Image") {
            steps {

                sh """
                    docker build \
                    -t ${IMAGE_NAME}:${BUILD_NUMBER} \
                    -f Assignment/Assignment5/app/Dockerfile \
                    Assignment/Assignment5/app
                """

            }
        }


        stage("DockerHub Login") {
            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS'
                    )
                ]) {

                    sh '''
                        echo $PASS | docker login \
                        -u $USER \
                        --password-stdin
                    '''

                }

            }
        }


        stage("Push Image") {
            steps {

                echo "Pushing Docker image to DockerHub..."

                sh """

                    docker tag ${IMAGE_NAME}:${BUILD_NUMBER} \
                    ${IMAGE_NAME}:latest


                    docker push ${IMAGE_NAME}:${BUILD_NUMBER}


                    docker push ${IMAGE_NAME}:latest

                """

            }
        }


        stage("Deploy") {
            steps {

                withKubeConfig([
                    credentialsId: 'my-kubeconfig'
                ]) {

                    sh """

                        echo "Deploying application..."


                        kubectl apply \
                        -f Assignment/Assignment5/K8s/namespace.yaml


                        kubectl apply \
                        -f Assignment/Assignment5/K8s/development.yaml


                        kubectl apply \
                        -f Assignment/Assignment5/K8s/service.yaml


                        kubectl rollout restart \
                        deployment/${DEPLOYMENT_NAME} \
                        -n ${NAMESPACE}


                        kubectl rollout status \
                        deployment/${DEPLOYMENT_NAME} \
                        -n ${NAMESPACE}


                        kubectl get pods \
                        -n ${NAMESPACE} \
                        -l app=node-app

                    """

                }

            }
        }

    }


    post {

        always {
            echo "======== Pipeline Finished ========"
        }


        success {
            echo "======== Pipeline executed successfully ========"
        }


        failure {
            echo "======== Pipeline execution failed ========"
        }

    }

}