pipeline{
    agent any

    environment{
        IMAGE_NAME= "deekshithc1/simplenodeapp"
    }
    stages{
        stage("Checkout Code"){
            steps{
                echo "checkout scm"
            }
        }
        stage("Build"){
            steps {
                sh '''
                docker build -t ${IMAGE_NAME}:latest \
                -f Assignment/Assignment5/app/Dockerfile \
               Assignment/Assignment5/app
                '''
            }
        } 
        }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
    }